
default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: furima_48556_development

test:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: furima_48556_test

production:
  <<: *default
  database: furima_48556_production
  username: furima_48556
  adapter: postgresql
  password: <%= ENV["FURIMA_48556_DATABASE_PASSWORD"] %>
